#!/bin/bash
# Created  2024-05-22
# Modified 2024-05-22

for DIR in $(find ~/scripts /www/git -type d -name .git);
do
    cd $DIR;
    cd ..;
    TODO=$(git status | grep modified | wc -l);

    if [ "$TODO" -gt 0 ];
    then
        echo -e "$(pwd)\n===================================\n$(git status)\n===================================\n$(git diff)" | less -SM;
    fi;
done

cd "$(dirname $0)";

